<?php

/**
 * @file views_kanban_style.module
 */

/**
 * Implements hook_views_api() 
 */
function views_kanban_style_views_api() {
    return array('api' => 3);
}

/**
 * Implements hook_menu()
 */
function views_kanban_style_menu() {
    return array(
        'views_kanban_style_update/%/%/%' => array(
            'page callback' => 'ajax_update_node',
            'page arguments' => array(1, 2, 3),
            'access arguments' => array('access content'),
            'type' => MENU_CALLBACK,
        ),
    );
}

function ajax_update_node($nid, $field, $value) {
    $node = node_load($nid);
    if($node) {
        $node->{$field}['und'][0]['value'] = $value;
        node_save($node);
        drupal_json_output(TRUE);
    } 
    
}